spring:
  application:
    name: medicalrecord-service
  datasource:
    url: "jdbc:${DB_URL_MEDICAL_RECORD}"
    username: ${DB_USERNAME_MEDICAL_RECORD}
    password: ${DB_PASSWORD_MEDICAL_RECORD}
    driver-class-name: "org.postgresql.Driver"
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/