spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: lb://auth-service
              predicates:
              - Path=/api/auth/**, /api/roles/**

            - id: users-service
              uri: lb://userprofile-service
              predicates:
                - Path=/api/users/**, /api/doctors/**, /api/patients/**, /api/specialties/**

            - id: absence-service
              uri: lb://scheduling-service
              predicates:
                - Path=/api/doctor-absences/**

            - id: scheduling-service
              uri: lb://scheduling-service
              predicates:
                - Path=/api/schedules/**

            - id: appointment-service
              uri: lb://appointment-service
              predicates:
                - Path=/api/appointments/**

            - id: payment-service
              uri: lb://payment-service
              predicates:
                - Path=/api/payments/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
    org.springframework.cloud.gateway: TRACE

server:
  port: 8080