server:
  port: 0
spring:
  application:
    name: payment-service
  datasource:
    url: "jdbc:${DB_URL_PAYMENT}"
    username: ${DB_USERNAME_PAYMENT}
    password: ${DB_PASSWORD_PAYMENT}
    driver-class-name: "org.postgresql.Driver"
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
vnpay:
  version: "2.1.0"
  command: "pay"
  locale: "vn"
  currCode: "VND"
  orderType: "billpayment"
  tmnCode: "${TMN_CODE}"
  paymentUrl: "${PAY_URL}"
  hashSecret: "${SECRET_KEY}"
  returnUrl: "${RETURN_URL}"
  refundUrl: "${REFUND_URL}"
  query-url: "${QUERY_URL}"

payment:
  query:
    safety-days-before: 7        # Chỉ query payment tạo trong 7 ngày gần đây
    min-minutes-before-query: 5  # Đợi ít nhất 5 phút trước khi query
    max-hours-for-query: 24      # Không query payment cũ hơn 24 giờ
    query-enabled: true          # Enable/disable tính năng query
    allow-old-payment-query: false # Có cho phép query payment cũ không

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
