eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    registry-sync-retry-wait-ms: 0
    wait-time-in-ms-when-sync-empty: 0
server:
  port: 8761