package org.project.enums;

public enum SagaStep {
    APPOINTMENT_CREATED,
    SLOT_RESERVATION,
    PATIENT_VALIDATION,
    DOCTOR_VALIDATION,
    COMPLETED,
    PAYMENT_COMPLETED,
    PAYMENT_FAILED_COMPENSATING,
    PAYMENT_FAILED_COMPENSATED
}
